#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libunibreak
Version  : 5.1
Release  : 1
URL      : https://github.com/adah1972/libunibreak/releases/download/libunibreak_5_1/libunibreak-5.1.tar.gz
Source0  : https://github.com/adah1972/libunibreak/releases/download/libunibreak_5_1/libunibreak-5.1.tar.gz
Summary  : Library to implement Unicode algorithms for line and word breaking
Group    : Development/Tools
License  : Zlib
Requires: libunibreak-lib = %{version}-%{release}
Requires: libunibreak-license = %{version}-%{release}
BuildRequires : file-bin
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
LIBUNIBREAK
===========
Overview
--------
breaking and word breaking algorithms as described in [Unicode Standard
Annex 14][1] and [Unicode Standard Annex 29][2].  Check the project's
[home page][3] for up-to-date information.

%package dev
Summary: dev components for the libunibreak package.
Group: Development
Requires: libunibreak-lib = %{version}-%{release}
Provides: libunibreak-devel = %{version}-%{release}
Requires: libunibreak = %{version}-%{release}

%description dev
dev components for the libunibreak package.


%package lib
Summary: lib components for the libunibreak package.
Group: Libraries
Requires: libunibreak-license = %{version}-%{release}

%description lib
lib components for the libunibreak package.


%package license
Summary: license components for the libunibreak package.
Group: Default

%description license
license components for the libunibreak package.


%prep
%setup -q -n libunibreak-5.1
cd %{_builddir}/libunibreak-5.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1675296352
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1675296352
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libunibreak
cp %{_builddir}/libunibreak-%{version}/LICENCE %{buildroot}/usr/share/package-licenses/libunibreak/b732f65dd876b409a3078bcfa24998526322bb63 || :
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/graphemebreak.h
/usr/include/linebreak.h
/usr/include/linebreakdef.h
/usr/include/unibreakbase.h
/usr/include/unibreakdef.h
/usr/include/wordbreak.h
/usr/lib64/libunibreak.so
/usr/lib64/pkgconfig/libunibreak.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libunibreak.so.5
/usr/lib64/libunibreak.so.5.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libunibreak/b732f65dd876b409a3078bcfa24998526322bb63
